name: iot_app
description: "WellSync - IoT & AI Based Digital Wellness Assistant"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  wifi_scan: ^0.4.1+2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  network_info_plus: ^6.1.4
  camera: ^0.11.1
  google_mlkit_face_detection: ^0.13.1
  cloud_firestore: ^5.6.7
  path_provider: ^2.1.5
  intl: ^0.20.2
  google_generative_ai: ^0.4.7
  equatable: ^2.0.7
  flutter_markdown: ^0.7.7+1
  fl_chart: ^0.71.0
  audioplayers: ^6.4.0
  flutter_dotenv: ^5.2.1
  flutter_custom_clippers: ^2.1.0
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons8-air-quality-96.png
    - assets/icons8-google-96.png
    - assets/unknown-icon.jpg
    - assets/WellSync_logo.png
    - assets/bg_Card1.png
    - assets/bg_Card2.png
    - assets/bg_Card3.png
    - assets/bg_Card4.png
    - assets/icons8-doctor.png
    - assets/plant-100.png
    - assets/audio/careless_whisper_on_one_guitar.mp3
    - assets/audio/electra.mp3
    - assets/audio/narvent_distant_echoes.mp3
    - assets/audio/piano_relaxing_sleep music.mp3
    - assets/audio/we_can_fly.mp3
    - assets/audio/weightless.mp3
