name: iot_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  wifi_iot: ^0.3.19+2
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  app_settings: ^6.1.1
  wifi_scan: ^0.4.1+2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  network_info_plus: ^6.1.4
  multicast_dns: ^0.3.3
  network_tools: ^5.0.6
  image_picker: ^1.1.2
  image: ^4.5.4
  camera: ^0.11.1
  flutter_foreground_task: ^9.1.0
  google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons8-air-quality-96.png
    - assets/icons8-google-96.png
    - assets/models/mobilefacenet.tflite
    - assets/unknown-icon.jpg
